name: commit

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23"
      - uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=2m
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: docker compose up -d mongo

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23"

      - name: tests-unit
        run: go test -v ./internal/... ./config/...

      - name: tests-e2e
        run: go test -v ./test/...

  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
      - name: Semantic release
        uses: go-semantic-release/action@v1
        id: release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Goreleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOVERSION: "1.23"
        with:
          args: release

